version: "3.3"

services:
  database:
    image: mysql:5.7.32
    container_name: mysql
    restart: always
    ports:
      - 8082:3306
    volumes:
      - ./database:/var/lib/mysql
      - ./logs:/var/log/apache2  
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: wpuser
      MYSQL_DATABASE: wordpress_database
      MYSQL_PASSWORD: mypass
  wordpress:
    depends_on:
      - database
    image: wordpress:5.7.2
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_NAME: wordpress_database
      WORDPRESS_DB_PASSWORD: mypass
      WORDPRESS_TABLE_PREFIX: local_